### ISSUE TITLE
Payment status is not updating after getting successurl from payment gateway

### ISSUE THREAD

**Issue by sahiliotasol** [moltin/js-sdk#28]
Using javascript - sdk

After redirecting to success url by making successful payment from payment gateway,  its status is not updating in the Moltin and it remains as 'Unpaid' status.

can you please help me to resolve this issue?

**Comment by AndreaPravato** [comment]
This is critical and urgent for us

**Comment by AndreaPravato** [comment]
We are using Paypal Express

**Comment by AndreaPravato** [comment]
with a sandbox (test) paypal account

**Comment by AJSturrock** [comment]
Hey guys, 

Once you get back to your return_url on your site you will need to make an API call to update the order status to "paid" (make sure to include the order ID in the return_url so you have a reference!). 

Unfortunately you won't be able to do this with clientside javascript and this won't automatically update stock levels. 

We are looking into a way for users to set a PayPal IPN to a moltin URL instead so that we can get a payment confirmation from PayPal (right now we don't receive anything).

**Comment by AndreaPravato** [comment]
Hi! Thanks. Do you have an ETA for that feature?

**Comment by AJSturrock** [comment]
I've opened an internal issue and referenced this one. Will need to be assigned to a member of the team first before we can give any ETAs

**Comment by AndreaPravato** [comment]
@AJSturrock  Are there news about ETA?
