### ISSUE TITLE
401 and CORS issue

### ISSUE THREAD

**Issue by nehero** [moltin/js-sdk#63]
Getting a `401` error on `/api/v1/products` and

> XMLHttpRequest cannot load https://api.molt.in/v1/products. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 401.

Building the app using Next.js / react. You don't need `moltin.Authenticate()` to list the products, correct?

Contrived example below at what I'm trying to do

```javascript
import Moltin from 'moltin'

// ...

componentDidMount() {
  this.setState({
     moltin: new Moltin({publicId: 'XXX'});
  });
}

_getProducts() {
  console.log(this.state.moltin.Product.List());
}

// ...
```

**Comment by ynnoj** [comment]
@nehero It looks like you're hitting the `v1` endpoints - is this intended? If so, you need to wrap your API calls in an `Authenticate` [call](https://github.com/moltin/js-sdk#usage).

Otherwise you'll need to install the newer package to use with `v2`.

```bash
npm install moltin@beta
```

Let me know if this helps 🙃

**Comment by nehero** [comment]
That gives me the error 

```
These modules were not found:

* fs in ./~/node-localstorage/LocalStorage.js, ./~/graceful-fs/graceful-fs.js and 1 other

To install it, you can run: npm install --save fs
```

I'm assuming it's trying to pull the node version instead of the client one? Is there a client moltin sdk available on NPM?

**Comment by ynnoj** [comment]
@nehero That documentation is from the `V1` branch of the repository. You'll find the README for the `V2` compatible package [here](https://github.com/moltin/js-sdk/tree/master#usage). A lot of this still in flux and work is still being done toward a stable release, hence why the package is tagged `beta` and the old branch is the _default_ here on GitHub.

The problem is occurring because of the lack of `localStorage` on the [server](https://github.com/moltin/js-sdk/blob/master/src/factories/storage.js#L5). I'll be working to fix that today, but in the meantime adding the below (👇)  to your *webpack* config _should_ fix the issue you're seeing.

```js
node: {
  fs: 'empty'
}
```
